In [1]:
import pandas as pd
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
def create_real_fips(ffips):
    if (len(ffips) == 1) or (len(ffips) == 4):
        return '0'+ffips
    else:
        return ffips

## CENSUS AGE COUNTS

Source: [ACS 2018, 5-year](https://data.census.gov/cedsci/table?q=age&g=0100000US.050000&tid=ACSDP5Y2018.DP05&t=Age%20and%20Sex&vintage=2018&hidePreview=true&tp=true)

In [3]:
trows = ['GEO_ID','NAME','DP05_0001E','DP05_0005E','DP05_0006E','DP05_0007E',
         'DP05_0008E','DP05_0009E','DP05_0010E','DP05_0011E','DP05_0012E',
         'DP05_0013E','DP05_0014E','DP05_0015E','DP05_0016E','DP05_0017E',
         'DP05_0018E','DP05_0023E','DP05_0024E']

age = pd.read_csv('../data/ACSDP5Y2018.DP05_data_with_overlays_2020-03-17T093715.csv',
                        usecols=trows)

col_rename = {'DP05_0001E':'pop','DP05_0005E':'pop_under5','DP05_0006E':'pop_5to9','DP05_0007E':'pop_10to14',
             'DP05_0008E':'pop_15to19','DP05_0009E':'pop_20to24','DP05_0010E':'pop_25to34',
              'DP05_0011E':'pop_35to44','DP05_0012E':'pop_45to54','DP05_0013E':'pop_55to59',
              'DP05_0014E':'pop_60to64','DP05_0015E':'pop_65to74','DP05_0016E':'pop_75to84',
              'DP05_0017E':'pop_85plus','DP05_0018E':'median_age','DP05_0023E':'pop_62plus',
              'DP05_0024E':'pop_65plus'}
age = age.rename(columns=col_rename)

#remove the line that contains the hr column titles
age = age.loc[~(age.index == 0)]
age['cnty_fips'] = age['GEO_ID'].str[-5:]
age['pop_62plus'] = pd.to_numeric(age['pop_62plus'],errors='coerce')
age['pop_65plus'] = pd.to_numeric(age['pop_65plus'],errors='coerce')
age['pop_85plus'] = pd.to_numeric(age['pop_85plus'],errors='coerce')

age.set_index('cnty_fips', inplace=True)

/Users/akanik/.virtualenvs/covid19/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (235,251,255,259,263,267,271,275,279,283,287,291,295,299,303,323,327) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
age.head()

                   GEO_ID                     NAME     pop pop_under5 pop_5to9 pop_10to14 pop_15to19 pop_20to24 pop_25to34 pop_35to44 pop_45to54 pop_55to59 pop_60to64 pop_65to74 pop_75to84  pop_85plus median_age  pop_62plus  pop_65plus
cnty_fips
01001      0500000US01001  Autauga County, Alabama   55200       3263     4009       3570       3855       3337       7064       7374       7853       4131       2694       4711       2524         815       37.8        9403        8050
01003      0500000US01003  Baldwin County, Alabama  208107      11609    11689      14323      12707      10790      23326      25377      28330      14440      14851      24551      12165        3949       42.8       49811       40665
01005      0500000US01005  Barbour County, Alabama   25782       1390     1450       1677       1434       1658       3675       3104       3452       1657       1651       2820       1392         422       39.9        5658        4634
01007      0500000US01007     Bibb County, Alabama   22527       1275     1178       1289       1514       1491       3075       2895       3439       1494       1216       2122       1112         427       39.9        4323        3661
01009      0500000US01009   Blount County, Alabama   57645       3485     3632       3995       3717       3189       6786       7153       7947       3895       3613       6132       3235         866       40.8       12400       10233

## CENSUS AGE PERCENTAGES
Source: [ACS 2018, 5-year](https://data.census.gov/cedsci/table?q=age&g=0100000US.050000&tid=ACSDP5Y2018.DP05&t=Age%20and%20Sex&vintage=2018&hidePreview=true&tp=true)

In [5]:
prows = ['GEO_ID','NAME','DP05_0001E','DP05_0005PE','DP05_0006PE','DP05_0007PE',
         'DP05_0008PE','DP05_0009PE','DP05_0010PE','DP05_0011PE','DP05_0012PE',
         'DP05_0013PE','DP05_0014PE','DP05_0015PE','DP05_0016PE','DP05_0017PE',
         'DP05_0018E','DP05_0023PE','DP05_0024PE']

perc_age = pd.read_csv('../data/ACSDP5Y2018.DP05_data_with_overlays_2020-03-17T093715.csv',
                        usecols=prows)

col_rename = {'DP05_0001E':'pop','DP05_0005PE':'perc_under5','DP05_0006PE':'perc_5to9','DP05_0007PE':'perc_10to14',
              'DP05_0008PE':'perc_15to19','DP05_0009PE':'perc_20to24','DP05_0010PE':'perc_25to34',
              'DP05_0011PE':'perc_35to44','DP05_0012PE':'perc_45to54','DP05_0013PE':'perc_55to59',
              'DP05_0014PE':'perc_60to64','DP05_0015PE':'perc_65to74','DP05_0016PE':'perc_75to84',
              'DP05_0017PE':'perc_85plus','DP05_0018E':'median_age','DP05_0023PE':'perc_62plus',
              'DP05_0024PE':'perc_65plus'}
perc_age = perc_age.rename(columns=col_rename)

#remove the line that contains the hr column titles
perc_age = perc_age.loc[~(perc_age.index == 0)]
perc_age['cnty_fips'] = perc_age['GEO_ID'].str[-5:]
perc_age['perc_62plus'] = pd.to_numeric(perc_age['perc_62plus'],errors='coerce')
perc_age['perc_65plus'] = pd.to_numeric(perc_age['perc_65plus'],errors='coerce')
perc_age['perc_85plus'] = pd.to_numeric(perc_age['perc_85plus'],errors='coerce')

perc_age.set_index('cnty_fips', inplace=True)

/Users/akanik/.virtualenvs/covid19/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (235,253,257,261,265,269,273,277,281,285,289,293,297,301,303,325,329) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
perc_age.head()

                   GEO_ID                     NAME     pop perc_under5 perc_5to9 perc_10to14 perc_15to19 perc_20to24 perc_25to34 perc_35to44 perc_45to54 perc_55to59 perc_60to64 perc_65to74 perc_75to84  perc_85plus median_age  perc_62plus  perc_65plus
cnty_fips
01001      0500000US01001  Autauga County, Alabama   55200         5.9       7.3         6.5         7.0         6.0        12.8        13.4        14.2         7.5         4.9         8.5         4.6          1.5       37.8         17.0         14.6
01003      0500000US01003  Baldwin County, Alabama  208107         5.6       5.6         6.9         6.1         5.2        11.2        12.2        13.6         6.9         7.1        11.8         5.8          1.9       42.8         23.9         19.5
01005      0500000US01005  Barbour County, Alabama   25782         5.4       5.6         6.5         5.6         6.4        14.3        12.0        13.4         6.4         6.4        10.9         5.4          1.6       39.9         21.9         18.0
01007      0500000US01007     Bibb County, Alabama   22527         5.7       5.2         5.7         6.7         6.6        13.7        12.9        15.3         6.6         5.4         9.4         4.9          1.9       39.9         19.2         16.3
01009      0500000US01009   Blount County, Alabama   57645         6.0       6.3         6.9         6.4         5.5        11.8        12.4        13.8         6.8         6.3        10.6         5.6          1.5       40.8         21.5         17.8

## DISEASE DATA: Diabetes

Rates are percentages of the population. Rate out of 100 people.

Source: Dwyer-Lindgren L, Mackenbach JP, van Lenthe FJ, Flaxman AD, Mokdad AH. Diagnosed and undiagnosed diabetes prevalence by county in the US, 1999–2012. Diabetes Care. 2016 August 23; 39:1556–1562. doi: 10.2337/dc16-0678. via [The Institute for Health Metrics and Evaluation (IHME) Global Health Data Exchange (GHDx)](http://ghdx.healthdata.org/us-data)

In [7]:
diabetes_cols = ['Location','FIPS','Prevalence, 2012, Both Sexes']
diabetes = pd.read_excel('../data/IHME_USA_COUNTY_DIABETES_PREVALENCE_1999_2012_NATIONAL_Y2016M08D23.XLSX',
                             sheet_name='Total', skiprows=[0], dtype={'FIPS':str,'Prevalence, 2012, Both Sexes':float})
diabetes = diabetes[diabetes_cols]

In [8]:
diabetes = diabetes.dropna(subset=['FIPS'])
diabetes['cnty_fips'] = diabetes['FIPS'].apply(lambda x: create_real_fips(x))
diabetes['state_fips'] = diabetes['cnty_fips'].str[:2]

diabetes_2012 = diabetes[['Location','cnty_fips','state_fips','Prevalence, 2012, Both Sexes']]
diabetes_2012.rename(columns={'Prevalence, 2012, Both Sexes':'diabetes_rate'}, inplace=True)

diabetes_2012.set_index('cnty_fips', inplace=True)

/Users/akanik/.virtualenvs/covid19/lib/python3.7/site-packages/pandas/core/frame.py:4133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [9]:
print(len(diabetes_2012))
diabetes_2012.head()

3193

                 Location state_fips  diabetes_rate
cnty_fips
01                Alabama         01          16.19
01001      Autauga County         01          15.45
01003      Baldwin County         01          13.44
01005      Barbour County         01          19.36
01007         Bibb County         01          16.68

## DISEASE DATA: Cardiovascular Disease

Rates are deaths per 100,000 population.

Source: Roth GA, Dwyer-Lindgren, Bertozzi-Villa A, Stubbs RW, Morozoff C, Naghavi M, Mokdad AH, Murray CJL. Trends and patterns of geographic variation in cardiovascular mortality among US counties, 1980–2014. JAMA. 2017 May 16. via [The Institute for Health Metrics and Evaluation (IHME) Global Health Data Exchange (GHDx)](http://ghdx.healthdata.org/us-data)

In [10]:
cvd_data = pd.read_excel('../data/IHME_USA_COUNTY_CVD_MORTALITY_RATES_1980_2014_NATIONAL_Y2017M05D16.XLSX',
                       sheet_name='Cardiovascular diseases',skiprows=[0],dtype={'FIPS':str})

In [11]:
cvd_2014 = cvd_data[['Location', 'FIPS', 'Mortality Rate, 2014*','% Change in Mortality Rate, 1980-2014']]
cvd_2014 = cvd_2014.rename(columns={'Mortality Rate, 2014*':'cvd_rate',
                                    '% Change in Mortality Rate, 1980-2014':'cvd_chg_1980_2014'})
cvd = cvd_2014['cvd_rate'].str.split(pat = "(",expand=True)
cvd_2014['cvd_rate'] = cvd[0].astype('float64')

chg = cvd_2014['cvd_chg_1980_2014'].str.split(pat = "(",expand=True)
cvd_2014['cvd_chg_1980_2014'] = chg[0].astype('float64')

cvd_2014 = cvd_2014.dropna(subset=['FIPS'])
cvd_2014['cnty_fips'] = cvd_2014['FIPS'].apply(lambda x: create_real_fips(x))
cvd_2014['state_fips'] = cvd_2014['cnty_fips'].str[:2]

cvd_2014 = cvd_2014[['Location', 'cnty_fips', 'state_fips', 'cvd_rate', 'cvd_chg_1980_2014']]
cvd_2014.set_index('cnty_fips', inplace=True)

In [12]:
print(len(cvd_2014))
cvd_2014.head()

3193

                          Location state_fips  cvd_rate  cvd_chg_1980_2014
cnty_fips
01                         Alabama         01    310.59             -39.91
01001      Autauga County, Alabama         01    316.36             -42.76
01003      Baldwin County, Alabama         01    272.04             -38.96
01005      Barbour County, Alabama         01    255.09             -50.52
01007         Bibb County, Alabama         01    378.09             -31.09

## DISEASE DATA: Chronic Respiratory Disease

Rates are deaths per 100,000 population.

Source: Dwyer-Lindgren L, Bertozzi-Villa A, Stubbs RW, Morozoff C, Shirude S, Naghavi M, Mokdad AH, Murray CJL. Trends and patterns of differences in chronic respiratory disease mortality among US counties, 1980–2014. JAMA. 25 Sept 2017; 318(12):1136-1149. doi:10.1001/jama.2017.11747. via [The Institute for Health Metrics and Evaluation (IHME) Global Health Data Exchange (GHDx)](http://ghdx.healthdata.org/us-data)

In [13]:
crd_data = pd.read_excel('../data/IHME_USA_COUNTY_RESP_DISEASE_MORTALITY_1980_2014_NATIONAL_Y2017M09D26.xlsx',
                       sheet_name='Chronic respiratory diseases',skiprows=[0],dtype={'FIPS':str})

In [14]:
crd_2014 = crd_data[['Location', 'FIPS', 'Mortality Rate, 2014*','% Change in Mortality Rate, 1980-2014']]
crd_2014 = crd_2014.rename(columns={'Mortality Rate, 2014*':'crd_rate',
                                    '% Change in Mortality Rate, 1980-2014':'crd_chg_1980_2014'})

crd = crd_2014['crd_rate'].str.split(pat = "(",expand=True)
crd_2014['crd_rate'] = crd[0].astype('float64')

chg = crd_2014['crd_chg_1980_2014'].str.split(pat = "(",expand=True)
crd_2014['crd_chg_1980_2014'] = chg[0].astype('float64')

crd_2014 = crd_2014.dropna(subset=['FIPS'])
crd_2014['cnty_fips'] = crd_2014['FIPS'].apply(lambda x: create_real_fips(x))
crd_2014['state_fips'] = crd_2014['cnty_fips'].str[:2]

crd_2014 = crd_2014[['Location', 'cnty_fips', 'state_fips', 'crd_rate', 'crd_chg_1980_2014']]
crd_2014.set_index('cnty_fips', inplace=True)

In [15]:
print(len(crd_2014))
crd_2014.head()

3193

                          Location state_fips  crd_rate  crd_chg_1980_2014
cnty_fips
01                         Alabama         01     73.44              73.08
01001      Autauga County, Alabama         01     81.79              75.67
01003      Baldwin County, Alabama         01     54.28              46.10
01005      Barbour County, Alabama         01     69.82              62.98
01007         Bibb County, Alabama         01     84.49              83.11

## RISK ANALYSIS

We're going to combine covid-19 risk measure by county to create a county-by-county risk analysis.

Datasets defined in this notebook:
- `crd_2014` - Chronic respiratory disease mortality rates, deaths per 100,000, 2014
- `cvd_2014` - Cardiovascular disease mortality rates, deaths per 100,000, 2014
- `diabetes_2012` - Diabetes prevelance, percent of population who has diabetes, 2012
- `age` - Population by age of population, count of people in age groups, 2018 ACS 5-year
- `perc_age` - Population by age of population, percent age groups, 2018 ACS 5-year
- ~`beds_by_cnty` - CMS hospital count and bed data, 2017 CMS cost reports~

In [17]:
pop_merge = perc_age.join(age,how='left',lsuffix='_perc', rsuffix='_cnt')
cd_merge = cvd_2014.join(crd_2014,how='left',lsuffix='_cvd', rsuffix='_crd')
disease_merge = cd_merge.join(diabetes_2012,how='left',lsuffix='_cd', rsuffix='_dia')
risk_data = pop_merge.join(disease_merge,how='left',lsuffix='_pop', rsuffix='_dis')

In [18]:
keep_cols = ['GEO_ID_perc','state_fips_cvd', 'NAME_perc', 'pop_perc', 'median_age_perc',
             'perc_62plus', 'perc_65plus', 'perc_85plus',
             'pop_62plus', 'pop_65plus', 'pop_85plus',
             'cvd_rate', 'cvd_chg_1980_2014','crd_rate', 'crd_chg_1980_2014','diabetes_rate',
             #the columns below can be omitted if you want a shorter dataset
             'perc_under5', 'perc_5to9','perc_10to14', 'perc_15to19', 'perc_20to24', 
             'perc_25to34','perc_35to44', 'perc_45to54', 'perc_55to59', 'perc_60to64',
             'perc_65to74', 'perc_75to84',
             'pop_under5', 'pop_5to9', 'pop_10to14', 'pop_15to19', 'pop_20to24',
             'pop_25to34', 'pop_35to44', 'pop_45to54', 'pop_55to59', 'pop_60to64',
             'pop_65to74', 'pop_75to84']

risk_data = risk_data[keep_cols]
risk_data.rename(columns={'GEO_ID_perc':'geoid','state_fips_cvd':'state_fips','NAME_perc':'cnty_name',
                          'pop_perc':'population','median_age_perc':'median_age'}, inplace=True)

In [19]:
#Important to note that these are quartiles calculated from regional data only
#Should probably pull in all US
risk_data['us_diabetes_q'] = pd.qcut(risk_data['diabetes_rate'], 4, [1,2,3,4])
risk_data['us_cvd_q'] = pd.qcut(risk_data['cvd_rate'], 4, [1,2,3,4])
risk_data['us_crd_q'] = pd.qcut(risk_data['crd_rate'], 4, [1,2,3,4])
risk_data['us_62plus_q'] = pd.qcut(risk_data['perc_62plus'], 4, [1,2,3,4])

risk_data['us_diabetes_q'] = (risk_data['us_diabetes_q'].astype('category').cat.codes)+1
risk_data['us_cvd_q'] = (risk_data['us_cvd_q'].astype('category').cat.codes)+1
risk_data['us_crd_q'] = (risk_data['us_crd_q'].astype('category').cat.codes)+1
risk_data['us_62plus_q'] = (risk_data['us_62plus_q'].astype('category').cat.codes)+1

risk_data['us_q_total'] = risk_data['us_diabetes_q'] + risk_data['us_cvd_q'] + risk_data['us_crd_q'] + risk_data['us_62plus_q']

In [20]:
reorder_cols = ['geoid', 'state_fips','cnty_name','population', 'perc_62plus',
                'cvd_rate','crd_rate','diabetes_rate','us_diabetes_q',
                'us_cvd_q', 'us_crd_q', 'us_62plus_q', 'us_q_total',
                'cvd_chg_1980_2014', 'crd_chg_1980_2014',
                'perc_65plus', 'perc_85plus', 'pop_62plus', 'pop_65plus', 'pop_85plus',
                'perc_under5','perc_5to9', 'perc_10to14', 'perc_15to19', 'perc_20to24', 
                'perc_25to34','perc_35to44', 'perc_45to54', 'perc_55to59', 'perc_60to64',
                'perc_65to74', 'perc_75to84', 'pop_under5', 'pop_5to9', 'pop_10to14',
                'pop_15to19', 'pop_20to24', 'pop_25to34', 'pop_35to44', 'pop_45to54',
                'pop_55to59', 'pop_60to64', 'pop_65to74', 'pop_75to84', 'median_age']
risk_data = risk_data[reorder_cols]

In [21]:
risk_data.sort_values('us_q_total', ascending=False).head(10)

                    geoid state_fips                     cnty_name population  perc_62plus  cvd_rate  crd_rate  diabetes_rate  us_diabetes_q  us_cvd_q  us_crd_q  us_62plus_q  us_q_total  cvd_chg_1980_2014  crd_chg_1980_2014  perc_65plus  perc_85plus  pop_62plus  pop_65plus  pop_85plus perc_under5 perc_5to9 perc_10to14 perc_15to19 perc_20to24 perc_25to34 perc_35to44 perc_45to54 perc_55to59 perc_60to64 perc_65to74 perc_75to84 pop_under5 pop_5to9 pop_10to14 pop_15to19 pop_20to24 pop_25to34 pop_35to44 pop_45to54 pop_55to59 pop_60to64 pop_65to74 pop_75to84 median_age
cnty_fips
47049      0500000US47049         47    Fentress County, Tennessee      17994         25.3    392.80    111.34          16.22              4         4         4            4          16             -34.34              96.78         20.7          1.4        4561        3729         257         5.9       5.5         6.2         6.5         5.1         9.8          11          14         7.9         7.4        13.2         6.1       1063      990       1120       1162        923       1768       1971       2520       1413       1335       2382       1090         45
51580      0500000US51580         51      Covington city, Virginia       5582         26.5    330.95     84.35          16.33              4         4         4            4          16             -41.45             111.63         21.5          3.5        1482        1202         196         4.2         5         6.9         5.1         6.5          12        13.1        11.9         6.1         7.6        12.3         5.7        236      281        384        284        361        670        731        667        341        425        688        318       42.8
01075      0500000US01075         01         Lamar County, Alabama      13933         25.8    326.28     89.17          16.31              4         4         4            4          16             -39.75             120.87         21.1          2.5        3598        2938         342         5.0       6.3         6.7         6.2         4.7        10.6        11.2        13.5         7.6         7.0        11.3         7.3        699      878        935        867        661       1472       1562       1881       1065        975       1580       1016       44.5
48191      0500000US48191         48            Hall County, Texas       3074         29.0    329.16     86.98          16.56              4         4         4            4          16             -41.24             134.68         23.1          2.9         892         709          89           4       4.9         9.6         8.9         4.7         8.2        10.7        12.1         5.6         8.1        12.3         7.9        124      152        295        275        144        251        330        371        173        250        377        243       43.5
54055      0500000US54055         54  Mercer County, West Virginia      60486         25.5    316.56     98.27          16.37              4         4         4            4          16             -38.58              44.67         20.8          2.7       15418       12584        1612         5.8       6.5         4.8         5.8         6.2        11.9        11.4        12.3         6.9         7.7          12         6.1       3499     3919       2926       3485       3748       7225       6890       7416       4154       4640       7282       3690       42.7
13253      0500000US13253         13      Seminole County, Georgia       8437         26.6    321.14     73.54          16.69              4         4         4            4          16             -44.23              73.87         22.1          3.5        2247        1866         293         5.5       6.8         5.5         7.5         4.5         9.9        12.0        11.5         6.7         8.0        12.9         5.7        468      570        462        631        377        832       1016        969        568        678       1088        485       44.0
47087      0500000US47087         47     Jackson County, Tennessee      11615         26.2    387.98    100.53          15.96              4         4         4            4          16             -32.58             153.06         21.5          1.5        3044        2492         177         4.3       4.6         5.8         6.1         5.3        10.1        11.6        14.1         7.7         8.9        13.3         6.7        503      532        678        711        617       1172       1348       1635        890       1037       1540        775       46.6
48301      0500000US48301         48          Loving County, Texas        102         30.4    404.69     92.21          16.54              4         4         4            4          16             -26.78              63.75         24.5          0.0          31          25           0        18.6       4.9           0           0         2.9        10.8        10.8           0        13.7        13.7        21.6         2.9         19        5          0          0          3         11         11          0         14         14         22          3       55.4
01035      0500000US01035         01       Conecuh County, Alabama      12514         25.5    349.78     76.40          19.90              4         4         4            4          16             -34.49             135.95         21.6          2.5        3188        2707         312         5.7       7.1         4.6         7.0         4.9        10.3        10.8        12.8         8.6         6.6        13.1         6.1        715      894        572        872        613       1288       1351       1601       1075        826       1634        761       44.8
48315      0500000US48315         48          Marion County, Texas      10083         29.1    327.22     97.44          16.54              4         4         4            4          16             -34.99             146.21         25.2          1.5        2939        2544         148         4.3       5.3         5.5           6         3.8           9        10.1        13.6         8.4         8.8        14.9         8.9        435      536        554        606        379        911       1016       1367        851        884       1500        896       50.1

In [23]:
risk_data.reset_index().to_csv('../data/national-cnty-covid19-risk-analysis.csv', index=False)